[project]
name = "pythonproject"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "black>=25.1.0",
    "flake8>=7.3.0",
    "pyyaml>=6.0.2",
]
