sales_job:
  input:
    path: "s3a://staging/Finance/BHCF20240331/BHCF20240331.txt"
    format: "csv"
    options:
      header: "true"
      inferSchema: "true"
      sep: "^"
      lineSep: "\n"

  output:
    path: "s3a://bronze/Finance/BHCF20240331/"
    format: "parquet"
    mode: "overwrite"
sparkConf:
  spark.hadoop.fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
  spark.hadoop.fs.s3a.aws.credentials.provider: org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
  spark.hadoop.fs.s3a.access.key: admin
  spark.hadoop.fs.s3a.secret.key: password
  spark.hadoop.fs.s3a.endpoint: http://minio:9000
  spark.hadoop.fs.s3a.path.style.access: true
  spark.sql.defaultCatalog: spark_catalog
  spark.sql.extensions: org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
  spark.sql.catalog.spark_catalog: org.apache.iceberg.spark.SparkCatalog
  spark.sql.catalog.spark_catalog.io-impl: org.apache.iceberg.aws.s3.S3FileIO
  spark.sql.catalog.spark_catalog.type: rest
  spark.sql.catalog.spark_catalog.warehouse: s3://warehouse